### ISSUE TITLE
Enable user to hide/show the left-hand sidebar

### ISSUE THREAD

**Issue by digitalronin** [alphagov/tdt-documentation#69]
A 'show/hide' feature which collapsed the left-hand sidebar would make it easier to read wide tables or diagrams.

**Comment by m-green** [comment]
Hi @digitalronin - thank you for you suggestion! Unfortunately we don't think we'll be able to prioritise developing this. We'd always advise that documentation writers avoid wide tables or diagrams (and think hard about using tables and diagrams at all), because they're often a worse user experience than simple content - especially on mobile displays. I'll need to close this issue - hope that's ok.
